/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedResearchRouteImport } from './routes/_authenticated/research'
import { Route as AuthenticatedPlannerRouteImport } from './routes/_authenticated/planner'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes'
import { Route as AuthenticatedEmailRouteImport } from './routes/_authenticated/email'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedChatThreadIdRouteImport } from './routes/_authenticated/chat.$threadId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedResearchRoute = AuthenticatedResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlannerRoute = AuthenticatedPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmailRoute = AuthenticatedEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatThreadIdRoute =
  AuthenticatedChatThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/email': typeof AuthenticatedEmailRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/research': typeof AuthenticatedResearchRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/email': typeof AuthenticatedEmailRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/research': typeof AuthenticatedResearchRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/chat': typeof AuthenticatedChatRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/email': typeof AuthenticatedEmailRoute
  '/_authenticated/notes': typeof AuthenticatedNotesRoute
  '/_authenticated/planner': typeof AuthenticatedPlannerRoute
  '/_authenticated/research': typeof AuthenticatedResearchRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/chat'
    | '/dashboard'
    | '/email'
    | '/notes'
    | '/planner'
    | '/research'
    | '/api/chat'
    | '/chat/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/chat'
    | '/dashboard'
    | '/email'
    | '/notes'
    | '/planner'
    | '/research'
    | '/api/chat'
    | '/chat/$threadId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/sitemap.xml'
    | '/_authenticated/chat'
    | '/_authenticated/dashboard'
    | '/_authenticated/email'
    | '/_authenticated/notes'
    | '/_authenticated/planner'
    | '/_authenticated/research'
    | '/api/chat'
    | '/_authenticated/chat/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/research': {
      id: '/_authenticated/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof AuthenticatedResearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/planner': {
      id: '/_authenticated/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AuthenticatedPlannerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/email': {
      id: '/_authenticated/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof AuthenticatedEmailRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat/$threadId': {
      id: '/_authenticated/chat/$threadId'
      path: '/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AuthenticatedChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
  }
}

interface AuthenticatedChatRouteChildren {
  AuthenticatedChatThreadIdRoute: typeof AuthenticatedChatThreadIdRoute
}

const AuthenticatedChatRouteChildren: AuthenticatedChatRouteChildren = {
  AuthenticatedChatThreadIdRoute: AuthenticatedChatThreadIdRoute,
}

const AuthenticatedChatRouteWithChildren =
  AuthenticatedChatRoute._addFileChildren(AuthenticatedChatRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmailRoute: typeof AuthenticatedEmailRoute
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRoute
  AuthenticatedPlannerRoute: typeof AuthenticatedPlannerRoute
  AuthenticatedResearchRoute: typeof AuthenticatedResearchRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmailRoute: AuthenticatedEmailRoute,
  AuthenticatedNotesRoute: AuthenticatedNotesRoute,
  AuthenticatedPlannerRoute: AuthenticatedPlannerRoute,
  AuthenticatedResearchRoute: AuthenticatedResearchRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
